create table public.products (
  id serial not null,
  name character varying(255) not null,
  category character varying(100) not null,
  price numeric(10, 2) not null,
  brand character varying(100) null,
  description text null,
  discount character varying(50) null,
  rating numeric(2, 1) null default 0,
  reviews integer null default 0,
  stock integer null default 0,
  main_image_url character varying(500) not null,
  color1 character varying(50) null,
  color1_code character varying(10) null,
  color1_image1 character varying(500) null,
  color1_image2 character varying(500) null,
  color1_image3 character varying(500) null,
  color1_image4 character varying(500) null,
  color2 character varying(50) null,
  color2_code character varying(10) null,
  color2_image1 character varying(500) null,
  color2_image2 character varying(500) null,
  color2_image3 character varying(500) null,
  color2_image4 character varying(500) null,
  color3 character varying(50) null,
  color3_code character varying(10) null,
  color3_image1 character varying(500) null,
  color3_image2 character varying(500) null,
  color3_image3 character varying(500) null,
  color3_image4 character varying(500) null,
  color4 character varying(50) null,
  color4_code character varying(10) null,
  color4_image1 character varying(500) null,
  color4_image2 character varying(500) null,
  color4_image3 character varying(500) null,
  color4_image4 character varying(500) null,
  size1 character varying(20) null,
  size2 character varying(20) null,
  size3 character varying(20) null,
  size4 character varying(20) null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  profit numeric(10, 2) null default 0,
  size1_price numeric(10, 2) null,
  size2_price numeric(10, 2) null,
  size3_price numeric(10, 2) null,
  size4_price numeric(10, 2) null,
  color1_price numeric(10, 2) null,
  color2_price numeric(10, 2) null,
  color3_price numeric(10, 2) null,
  color4_price numeric(10, 2) null,
  warehouse text null,
  zone text null,
  constraint products_pkey primary key (id)
) TABLESPACE pg_default;
